name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    uses: streemtech/actions/.github/workflows/testaction.yml@main
    with: 
      names: '["daryl","jeffrey"]'