on:
  workflow_call:
    secrets:
      VPN_CONFIG:
        required: true
        description: "VPN configuration file text"
      KUBE_CONFIG:
        required: true
        description: "Kubernetes configuration file text"
      # OVPN_CLIENT_KEY:
      #   required: true
      #   description: "the certificate key"

    inputs:
      check_ip:
        required: true
        type: string
        description: "the IP pinged to check for a proper VPN connection."
      services:
        required: true
        type: string
        description: "a json array of service strings to call this workflow against."
      docker_registry_repo:
        required: true
        type: string
        description: "the repository of the registry to send the containers to"
      docker_registry:
        required: true
        type: string
        description: "destination docker registry"
      kube_version:
        required: true
        type: string
        description: "the kubernetes version used in azure."
      kube_namespace:
        required: true
        type: string
        description: "one of qa-test, qa-prod, test, prod. Determines the tags used in the docker containers."
      tag: 
        description: "the tag used for the deployment container"
        required: true
        type: string
      deployment_prefix:
        description: "the prefix used before the deployment name deployment/<PREFIX>asdf-deployment"
        required: true
        type: string
#Reusable Workflow. Not a composite action unf.


jobs:
  deployContainers:
    strategy:
      matrix:
        service: ${{fromJson(inputs.services)}}
    runs-on: ubuntu-latest

    steps:
      - uses: azure/setup-kubectl@v1
        with:
          version: ${{inputs.kube_version}}

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

      - run: 'echo "$VPN_CONFIG" > ./config.ovpn'
        name: create ovpn file
        shell: bash
        env:
          VPN_CONFIG: ${{secrets.VPN_CONFIG}}

      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v1"
        with:
          config_file: ./config.ovpn
          # client_key: ${{ secrets.OVPN_CLIENT_KEY }}

      - run: 'echo "$KUBE_CONFIG" > ./kube.config'
        name: create kube config file
        shell: bash
        env:
          KUBE_CONFIG: ${{secrets.KUBE_CONFIG}}

      - name: Check Connect VPN
        run: ping ${{inputs.check_ip}} -c 1

      - name: update image
        run: |
          kubectl --namespace=${{ inputs.kube_namespace }} --kubeconfig ./kube.config \
          set image deployment/${{inputs.deployment_prefix}}${{ matrix.service }}-deployment \
          ${{inputs.deployment_prefix}}${{ matrix.service }}=${{ inputs.docker_registry }}/${{ inputs.docker_registry_repo }}/${{ matrix.service }}:${{ inputs.tag }}

      - name: deploy
        run: |
          kubectl --namespace=${{ inputs.kube_namespace }} --kubeconfig ./kube.config \
          rollout restart deployment/${{inputs.deployment_prefix}}${{ matrix.service }}-deployment
