on:
  workflow_call:
    secrets:
      discord_webhook:
        required: true
        description: "value of the webhook to use for sending to discord"

    inputs:
      success:
        required: true
        type: boolean
        description: "if the particular embed should send as a success or not."
      ping_role_id:
        required: true
        type: string
        description: "the id of the role to ping."
      env_variant:
        required: true
        type: string
        description: "what environment the event occurred in."
      failure_reason:
        required: true
        type: string
        description: "what environment the event occurred in."
      github_repository:
        required: true
        type: string
        description: "the repository in question."
      github_server_url:
        required: true
        type: string
        description: "the github server url."
      github_run_id:
        required: true
        type: string
        description: "the run ID."

jobs:
  deployContainers:
    timeout-minutes: 2
    runs-on: self-hosted

    steps:
      - name: Discord Success Notification
        uses: sebastianpopp/discord-action@releases/v2
        if: ${{ inputs.success }}
        with:
          webhook: ${{ secrets.discord_webhook }}
          message: |
            [${{ inputs.github_repository }}](https://github.com/streemtech/${{ inputs.github_repository }}) deployed to `${{ inputs.env_variant }}`

      - name: Discord Fail Notification
        uses: sebastianpopp/discord-action@releases/v2
        if: ${{ !inputs.success }}
        with:
          webhook: ${{ secrets.discord_webhook }}
          message: |
            # ${{ inputs.github_repository }} Deployment Failure
            [${{ inputs.github_repository }}](https://github.com/streemtech/${{ inputs.github_repository }}) has failed in deploying to `${{ inputs.env_variant }}`
            See [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details
            ${{ inputs.ping_role_id }}
