on:
  workflow_call:
    secrets:
      discord_webhook:
        required: true
        description: "value of the webhook to use for sending to discord"

    inputs:
      success:
        required: true
        type: boolean
        description: "if the particular embed should send as a success or not."
      ping_role_id:
        required: true
        type: string
        description: "the id of the role to ping."
      env_variant:
        required: true
        type: string
        description: "what environment the event occurred in."
      failure_reason:
        required: true
        type: string
        description: "what environment the event occurred in."
      github_repository:
        required: true
        type: string
        description: "the repository in question."
      github_server_url:
        required: true
        type: string
        description: "the github server url."
      github_run_id:
        required: true
        type: string
        description: "the run ID."
#Reusable Workflow. Not a composite action unf.

jobs:
  deployContainers:
    runs-on: self-hosted

    steps:
      - name: Discord Success Notification
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ inputs.success }}
        with:
          username: Actions Bot
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          webhookUrl: ${{ secrets.discord_webhook }}
          severity: info
          details: Project ${{ inputs.github_repository }} has succeeded in deploying to ${{ inputs.env_variant }}
          text: ${{ inputs.github_server_url }}/${{ inputs.github_repository }}/actions

      - name: Discord Fail Notification
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ !inputs.success }}
        with:
          username: Actions Bot
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          webhookUrl: ${{ secrets.discord_webhook }}
          severity: error
          details: Project ${{ inputs.github_repository }} has failed in deploying to ${{ inputs.env_variant }}
          footer: ${{ inputs.failure_reason }}
          text: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} ${{ inputs.ping_role_id }}
          #TODO add role ping. <@&988658826599342120>
