on:
  workflow_call:
    secrets:
      # GO_MODULES_TOKEN:
      #   required: true
      #   description: "the token used to pull data from github, and checkout as needed."
      GITHUB_AUTH_TOKEN: #This can NOT be GITHUB_TOKEN as that is a pre-set secret.
        required: true
        description: "the token used to pull data from github, and checkout as needed."

    inputs:
      version:
        required: true
        type: boolean
        description: if the version should be incremented or not.
      go_private: 
        description: "the string sent to GOPRIVATE env var"
        type: string
        required: true
      skip_static: 
        description: "if static checking should be skipped"
        type: boolean
        required: false
        default: false
      skip_shadow: 
        description: "if shadowning should be skipped"
        type: boolean
        required: false
        default: false
      skip_lint: 
        description: "if linting should be skipped"
        type: boolean
        required: false
        default: false

    outputs:
      newTag:   
        description: "The full new tag cretaed"
        value: ${{ jobs.unitTests.outputs.newTag }}
      tagMajor: 
        description: "the major version of the tag"
        value: ${{ jobs.unitTests.outputs.tagMajor }}
      tagMinor: 
        description: "the minor version of the tag."
        value: ${{ jobs.unitTests.outputs.tagMinor }}
      tagPatch: 
        description: "the patch version of the tag."
        value: ${{ jobs.unitTests.outputs.tagPatch }}

#Reusable Workflow. Not a composite action unf.
jobs:
  unitTests:
    # strategy:
    #   matrix: 
    #     name: ${{fromJson(inputs.names)}}
    runs-on: ubuntu-latest
    outputs:
      newTag: ${{ steps.bump_tag.outputs.new_tag }}
      tagMajor: ${{ steps.semver_parser.outputs.major }}
      tagMinor: ${{ steps.semver_parser.outputs.minor }}
      tagPatch: ${{ steps.semver_parser.outputs.patch }}
    env:
      GOPRIVATE: ${{inputs.go_private}}

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.GITHUB_AUTH_TOKEN }}

      - name: Setup git config
        run:  git config --global url.https://${{ secrets.GITHUB_AUTH_TOKEN }}@github.com/.insteadOf https://github.com/

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: 1.18

      - name: restore go cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-goTests-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-goTests-

      - name: Generate
        run: go generate ./...

      - name: Test
        run: go test -v -coverprofile=c.out ./...

      - name: Generate Coverage Report
        run: go tool cover -html=c.out -o coverage.html

      - name: Shadow Test
        if: inputs.skip_shadow == false
        run: | 
          go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest
          shadow -strict ./...

      - name: Static Check
        if: inputs.skip_shadow == false
        run: | 
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...

      - name: golangci-lint
        if: inputs.skip_lint == false
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.46
          skip-pkg-cache: true
          skip-go-installation: true
          skip-build-cache: true


      - name: Archive Test Coverage
        uses: actions/upload-artifact@v2
        with:
          path: coverage.html
          name: coverage.html
          retention-days: 7

      - name: calculate test version number.
        id: bump_tag
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          DRY_RUN: true
      - name: Parse semver string
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: "${{ steps.bump_tag.outputs.new_tag }}"
