on:
  workflow_call:
    secrets:
      # GO_MODULES_TOKEN:
      #   required: true
      #   description: "the token used to pull data from github, and checkout as needed."
      GITHUB_AUTH_TOKEN: #This can NOT be GITHUB_TOKEN as that is a pre-set secret.
        required: true
        description: "the token used to pull data from github, and checkout as needed."
      discord_webhook:
        required: true
        description: "value of the webhook to use for sending to discord"

    inputs:
      version:
        required: true
        type: boolean
        description: if the version should be incremented or not.
      go_private:
        description: "the string sent to GOPRIVATE env var"
        type: string
        required: true
      skip_static:
        description: "if static checking should be skipped"
        type: boolean
        required: false
        default: false
      skip_shadow:
        description: "if shadowning should be skipped"
        type: boolean
        required: false
        default: false
      skip_lint:
        description: "if linting should be skipped"
        type: boolean
        required: false
        default: false
      github_repository:
        required: true
        type: string
        description: "the repository in question."
      github_server_url:
        required: true
        type: string
        description: "the github server url."
      github_run_id:
        required: true
        type: string
        description: "the run ID."

    outputs:
      newTag:
        description: "The full new tag cretaed"
        value: ${{ jobs.unitTests.outputs.newTag }}
      tagMajor:
        description: "the major version of the tag"
        value: ${{ jobs.unitTests.outputs.tagMajor }}
      tagMinor:
        description: "the minor version of the tag."
        value: ${{ jobs.unitTests.outputs.tagMinor }}
      tagPatch:
        description: "the patch version of the tag."
        value: ${{ jobs.unitTests.outputs.tagPatch }}

#Reusable Workflow. Not a composite action unf.
jobs:
  unitTests:
    # strategy:
    #   matrix:
    #     name: ${{fromJson(inputs.names)}}
    runs-on: ubuntu-latest
    outputs:
      newTag: ${{ steps.bump_tag.outputs.new_tag }}
      tagMajor: ${{ steps.semver_parser.outputs.major }}
      tagMinor: ${{ steps.semver_parser.outputs.minor }}
      tagPatch: ${{ steps.semver_parser.outputs.patch }}
    env:
      GOPRIVATE: ${{inputs.go_private}}

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.GITHUB_AUTH_TOKEN }}

      - name: Setup git config
        run: git config --global url.https://${{ secrets.GITHUB_AUTH_TOKEN }}@github.com/.insteadOf https://github.com/

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
          check-latest: true
          cache: true

      - name: Generate
        run: make gen
      - name: Generate Notification
        uses: rjstone/discord-webhook-notify@v1
        with:
          username: Actions Bot
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          webhookUrl: ${{ secrets.discord_webhook }}
          severity: info
          color: "#851ebd"
          description: | 
            Repository: ${{ inputs.github_repository }} 
            Step: Generate 
            URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}



      - name: Test
        run: go test -v -coverprofile=c.out ./...
      - name: Test Notification
        uses: rjstone/discord-webhook-notify@v1
        with:
          username: Actions Bot
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          webhookUrl: ${{ secrets.discord_webhook }}
          severity: info
          color: "#851ebd"
          description: | 
            Repository: ${{ inputs.github_repository }} 
            Step: Test 
            URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}



      - name: Generate Coverage Report
        run: go tool cover -html=c.out -o coverage.html

      - name: Shadow Test
        if: inputs.skip_shadow == false
        run: |
          go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest
          shadow -strict $(go list ./... | grep -v "api$")
      - name: Shadow Test Notification
        uses: rjstone/discord-webhook-notify@v1
        with:
          username: Actions Bot
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          webhookUrl: ${{ secrets.discord_webhook }}
          severity: info
          color: "#851ebd"
          description: | 
            Repository: ${{ inputs.github_repository }} 
            Step: Shadow Test 
            URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}



      - name: Static Check
        if: inputs.skip_static == false
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck $(go list ./... | grep -v "api$")
      - name: Static Check Notification
        uses: rjstone/discord-webhook-notify@v1
        with:
          username: Actions Bot
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          webhookUrl: ${{ secrets.discord_webhook }}
          severity: info
          color: "#851ebd"
          description: | 
            Repository: ${{ inputs.github_repository }} 
            Step: Static Check 
            URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}



      - name: golangci-lint
        if: inputs.skip_lint == false
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.46
          skip-pkg-cache: true
          skip-go-installation: true
          skip-build-cache: true
      - name: lint Notification
        uses: rjstone/discord-webhook-notify@v1
        with:
          username: Actions Bot
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          webhookUrl: ${{ secrets.discord_webhook }}
          severity: info
          color: "#851ebd"
          description: | 
            Repository: ${{ inputs.github_repository }} 
            Step: lint 
            URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}



      - name: Archive Test Coverage
        uses: actions/upload-artifact@v2
        with:
          path: coverage.html
          name: coverage.html
          retention-days: 7

      - name: calculate test version number.
        id: bump_tag
        uses: anothrNick/github-tag-action@1.52.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          DRY_RUN: ${{ !inputs.version }}

      - name: Parse semver string
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: "${{ steps.bump_tag.outputs.new_tag }}"
