on:
  workflow_call:
    secrets:
      GITHUB_AUTH_TOKEN: #This can NOT be GITHUB_TOKEN as that is a pre-set secret.
        required: true
        description: "the token used to pull data from github, and checkout as needed."

    inputs:
      go_private:
        description: "the string sent to GOPRIVATE env var"
        type: string
        required: true
      branch:
        description: "the branch to reference for updates"
        type: string
        required: true
      skip_static:
        description: "if static checking should be skipped"
        type: boolean
        required: false
        default: false
      skip_shadow:
        description: "if shadowing should be skipped"
        type: boolean
        required: false
        default: false
      skip_lint:
        description: "if linting should be skipped"
        type: boolean
        required: false
        default: false
      all:
        description: "if true, all deps will be updated, not just streemtech ones"
        type: boolean
        required: true

#Reusable Workflow. Not a composite action unf.
jobs:
  nightlyUpdate:
    timeout-minutes: 15
    runs-on: self-hosted
    env:
      GOPRIVATE: ${{inputs.go_private}}

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          persist-credentials: true
          token: ${{ secrets.GITHUB_AUTH_TOKEN }}
          ref: ${{inputs.branch}}

      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true
          cache: false

      - name: Setup git config
        run: git config --global url."https://x-oauth-basic:${{ secrets.GITHUB_AUTH_TOKEN }}@github.com".insteadOf "https://github.com"

      - name: "Update everything"
        if: ${{ inputs.all }}
        id: update_all
        run: |
          UPDATES=$(go list -u -f '{{if and (not .Main) (not (eq .Update nil)) }}{{.Path}} upgrading from {{.Version}} to {{.Update.Version}} {{end}}' -m all)
          go get -u ./...
          go mod tidy
          echo 'updates<<EOF' >> $GITHUB_OUTPUT
          echo "Updating all dependencies" >> $GITHUB_OUTPUT
          echo $UPDATES >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: "Update Streemtech"
        if: ${{ !inputs.all }}
        id: update
        run: |
          UPDATES=$(go list -u -f '{{if and (not .Main) (not (eq .Update nil)) }}{{.Path}} upgrading from {{.Version}} to {{.Update.Version}} {{end}}' -m all | grep streemtech)
          go get -u $(go list -f '{{if not .Main}}{{.Path}}{{end}}' -m all | grep streemtech)
          go mod tidy
          echo 'updates<<EOF' >> $GITHUB_OUTPUT
          echo "Updating dependencies" >> $GITHUB_OUTPUT
          echo $UPDATES >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: "re-generate as needed"
        run: |
          make gen

      #Run the tests to make sure everything is still functional
      - name: Test
        run: go test -v -coverprofile=c.out ./...

      - name: Generate Coverage Report
        run: go tool cover -html=c.out -o coverage.html

      - name: Shadow Test
        if: inputs.skip_shadow == false
        run: |
          go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest
          shadow -strict $(go list ./... | grep -v "api$")

      - name: Static Check
        if: inputs.skip_static == false
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck $(go list ./... | grep -v "api$")

      - name: golangci-lint
        if: inputs.skip_lint == false
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Archive Test Coverage
        uses: actions/upload-artifact@v2
        with:
          path: coverage.html
          name: coverage.html
          retention-days: 7

      - name: Commit & Push changes
        if: ${{ inputs.all }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-Update #patch\n\n${{steps.update_all.outputs.updates}}"
          branch: ${{inputs.branch}}

      - name: Commit & Push changes
        if: ${{ !inputs.all }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-Update #patch\n\n${{steps.update.outputs.updates}}"
          branch: ${{inputs.branch}}